### ISSUE TITLE
Test Benchmarks with gas metering code

### ISSUE THREAD

**Issue by AmeanAsad** [retrieval-markets-lab/bls-benches#2]
### Description:

Currently the benchmark results are from local testing. FVM adds some extra code to WASM (eg gas metering) which probably impacts the runtime of the benchmarks. Therefore we must run the benchmarks with this additional overhead to get more realistic results. 

### Tasks:
- [x] Compile the current individual tests to WASM bundles. 
- [x] Run the benchmarks to test. 
- [x] Add the gas metering code to the WASM bundle using https://github.com/filecoin-project/fvm-wasm-instrument/
- [ ] Run the benchmarks again to test with the additional code.
